-- Ckflix / MovieHub backend schema for Supabase (free Postgres)
-- Run this once in the Supabase SQL Editor (Dashboard > SQL Editor > New query)

-- Profiles: extra user info linked to Supabase Auth
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '',
  email text not null default '',
  created_at timestamptz not null default now()
);

-- Comments shown on the site
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  name text not null,
  text text not null,
  created_at timestamptz not null default now()
);

-- Newsletter subscribers
create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

-- Favorites (per user)
create table if not exists public.favorites (
  user_id uuid not null references auth.users (id) on delete cascade,
  movie_id bigint not null,
  created_at timestamptz not null default now(),
  primary key (user_id, movie_id)
);

-- Play counter per movie/TV id
create table if not exists public.plays (
  movie_id bigint primary key,
  count bigint not null default 1
);

-- Optional table of hand-picked classics (matches api.movies())
create table if not exists public.classics (
  id bigint generated by default as identity primary key,
  title text not null,
  poster text,
  backdrop text,
  video text not null,
  description text,
  genres text,
  year int default 0,
  rating numeric(3,1) default 0,
  duration text,
  trending boolean default false,
  plays bigint default 0
);

-- Increment play counter safely from the browser
create or replace function public.increment_play(p_movie_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.plays (movie_id, count)
  values (p_movie_id, 1)
  on conflict (movie_id) do update set count = public.plays.count + 1;
$$;

-- Row Level Security
alter table public.profiles enable row level security;
alter table public.comments enable row level security;
alter table public.subscribers enable row level security;
alter table public.favorites enable row level security;
alter table public.plays enable row level security;
alter table public.classics enable row level security;

-- Profiles: readable by everyone, only the owner can edit their own
drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select using (true);

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles for insert with check (auth.uid() = id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update using (auth.uid() = id);

-- Comments: anyone can read and post
drop policy if exists comments_read on public.comments;
create policy comments_read on public.comments for select using (true);

drop policy if exists comments_insert on public.comments;
create policy comments_insert on public.comments for insert with check (true);

-- Subscribers: anyone can sign up
drop policy if exists subscribers_insert on public.subscribers;
create policy subscribers_insert on public.subscribers for insert with check (true);

-- Favorites: only the owner can see or change their own
drop policy if exists favorites_read_own on public.favorites;
create policy favorites_read_own on public.favorites for select using (auth.uid() = user_id);

drop policy if exists favorites_insert_own on public.favorites;
create policy favorites_insert_own on public.favorites for insert with check (auth.uid() = user_id);

drop policy if exists favorites_delete_own on public.favorites;
create policy favorites_delete_own on public.favorites for delete using (auth.uid() = user_id);

-- Plays & classics: readable by everyone
drop policy if exists plays_read on public.plays;
create policy plays_read on public.plays for select using (true);

drop policy if exists classics_read on public.classics;
create policy classics_read on public.classics for select using (true);
