-- ============================================================
-- CKFLIX — SUPABASE SCHEMA
-- Run this whole file once in: Supabase Dashboard > SQL Editor
-- Then set yourself as admin (replace your@email.com at the end).
-- ============================================================

-- ---------- 1. profiles ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '',
  email text not null default '',
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles read own" on public.profiles;
create policy "profiles read own"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "profiles insert own" on public.profiles;
create policy "profiles insert own"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own"
  on public.profiles for update
  using (auth.uid() = id);

-- ---------- 2. helper: is the current user an admin? ----------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false)
$$;

-- ---------- 3. subscribers (newsletter) ----------
create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.subscribers enable row level security;

-- anyone can subscribe (no account needed)
drop policy if exists "subscribers insert public" on public.subscribers;
create policy "subscribers insert public"
  on public.subscribers for insert
  with check (true);

-- only the owner/admin can read the subscriber list
drop policy if exists "subscribers read admin" on public.subscribers;
create policy "subscribers read admin"
  on public.subscribers for select
  using (public.is_admin());

-- ---------- 4. comments ----------
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  name text not null default '',
  text text not null,
  created_at timestamptz not null default now()
);

alter table public.comments enable row level security;

drop policy if exists "comments read public" on public.comments;
create policy "comments read public"
  on public.comments for select
  using (true);

drop policy if exists "comments insert auth" on public.comments;
create policy "comments insert auth"
  on public.comments for insert
  with check (auth.uid() is not null);

-- only the owner/admin can delete comments
drop policy if exists "comments delete admin" on public.comments;
create policy "comments delete admin"
  on public.comments for delete
  using (public.is_admin());

-- ---------- 5. favorites ----------
create table if not exists public.favorites (
  user_id uuid references auth.users (id) on delete cascade,
  movie_id integer not null,
  created_at timestamptz not null default now(),
  primary key (user_id, movie_id)
);

alter table public.favorites enable row level security;

drop policy if exists "favorites own all" on public.favorites;
create policy "favorites own all"
  on public.favorites for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ---------- 6. classics (the movie catalog) ----------
create table if not exists public.classics (
  id integer primary key,
  title text not null,
  poster text,
  backdrop text,
  video text,
  description text,
  genres text[] default '{}',
  year text,
  rating numeric default 0,
  duration text,
  trending boolean default false,
  plays integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.classics enable row level security;

drop policy if exists "classics read public" on public.classics;
create policy "classics read public"
  on public.classics for select
  using (true);

-- ---------- 7. play counter ----------
create or replace function public.increment_play(p_movie_id integer)
returns void
language sql
security definer
set search_path = public
as $$
  update public.classics set plays = plays + 1 where id = p_movie_id;
$$;

-- ============================================================
-- 👑 MAKE YOURSELF THE OWNER / ADMIN
-- After you sign up on the site once, run this with your email:
-- ============================================================
-- UPDATE public.profiles SET is_admin = true WHERE email = 'your@email.com';
